<?php
/**
 * @file
 * Contains the constants that might be to be changed by aps.
 */

/**
 * Role used as the Super Administrator of the site.
 */
define('SLIDESORTER_ROLES_SUPER_ADMINISTRATOR', 'administrator');

/**
 * Used to grant access permissions to the User Manager
 */

define('SLIDESORTER_ROLES_CONTENT_ADMINISTRATOR', 'content administrator');

//define('SLIDESORTER_ROLES_CLIENT_MANAGER', 'client manager');

/**
 * Machine name of the Client Content Type.
 */
define('SLIDESORTER_CLIENT_CONTENT_TYPE', 'client');

/**
 * Machine name of the Client Content Type.
 */
//define('SLIDESORTER_PRODUCT_CONTENT_TYPE', 'product');

/**
 * OG Role used to identify Administrators of a group.
 */
define('SLIDESORTER_GROUP_ROLES_ADMINISTRATOR', 'administrator member');

/**
 * OG Role used to identify Managers of a group.
 */
define('SLIDESORTER_GROUP_ROLES_MANAGER', 'group manager');
